site_name: PlotJuggler. The timeseries visualization tool you deserve
pages:
    - Introduction: index.md
    - User Guide:
        - 'How to arrange your plots':  'arrange_plots.md'
        - 'Zoom and more':              'visualization_howto.md'
        - 'Load data':                  'load_data.md'
        - 'Streaming data':             'streaming_data.md'
        - 'The vertical tracker':       'tracker.md'
    - Plugins:
        - 'ROS plugins': 'ros_plugins.md'
    - About: about.md
 
