clone_depth: 5

build:
  verbosity: minimal

environment:
  matrix:
  - BUILD: 'Release'

configuration:
  - Release

#branches:
  #only:
    #- master

before_build:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - set PATH=C:\Qt\Tools\QtCreator\bin;C:\Qt\5.11\msvc2015\bin;%PATH%
  - mkdir build
  - cd build
  - set PATH=%QTDIR%\bin;%PATH%
  - cmd: if "%platform%"=="Win32" cmake "-G%GENERATOR32%" -DCMAKE_PREFIX_PATH="%QTDIR32%/lib/cmake/Qt5" ..
  - cmd: if "%platform%"=="x64"   cmake "-G%GENERATOR64%" -DCMAKE_PREFIX_PATH="%QTDIR64%/lib/cmake/Qt5" ..

build:
  parallel: true
  project: C:\projects\plotjuggler\build\PlotJuggler.sln

