sudo: required
dist: trusty
language: cpp

os:
  - linux
  
compiler:
  - gcc

before_install:

 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
 
 - sudo apt-get update -qq
 - sudo apt-get -y install -f qtbase5-dev qt5-default qttools5-dev-tools li
 - sudo apt-get -y install libboost-dev

script: 
 - git submodule foreach git pull origin master
 - cmake -DCMAKE_INSTALL_PREFIX=/app . 
 - make
 
notifications:
  email:
    recipients:
      - davide.faconti@gmail.com
    on_success: change
    on_failure: always
