language: cpp
compiler:
  - gcc

sudo: required
dist: trusty

script: cmake . && make 

before_script:

 - sudo apt-get update -qq
 - sudo apt-get --yes install qtbase5-dev

notifications:
  email:
    recipients:
      - davide.faconti@gmail.com
    on_success: change
    on_failure: always
