site_name: PlotJuggler

repo_name: 'facontidavide/PlotJuggler'
repo_url: https://github.com/facontidavide/PlotJuggler

use_directory_urls: false
theme: flatly

pages:
    - Introduction: index.md
    - User Guide:
        - 'Basics: how to visualize your data':      'visualization_howto.md'
        - 'Data Sources: Loaded vs streamed data':   'data_sources.md'
        - 'Vertical tracker and publishers':         'tracker.md'
    - Plugins:
        - 'ROS plugins': 'ros_plugins.md'
    - About: about.md
 
